version: '3.11'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - nbp-flask-app
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 'app.main:create_app()' --reload
    volumes:
      - ./:/webapp
    ports:
      - "8000:8000"
    networks:
      nbp-flask-app:
        aliases:
          - flask-app

networks:
  nbp-flask-app: