from enum import Enum


class Currency(Enum):
    THB = 'bat'
    USD = 'american dollar'
    AUD = 'australian dollar'
    HKD = 'hong kong dollar'
    CAD = 'canadian dollar'
    NZD = 'new zealand dollar'
    SGD = 'singapore dollar'
    EUR = 'euro'
    HUF = 'hungarian forint'
    CHF = 'swiss franc'
    GBP = 'pound sterling'
    UAH = 'ukrainian hryvnia'
    JPY = 'japanese yen'
    CZK = 'czech koruna'
    DKK = 'denmark krone'
    ISK = 'icelandic krona'
    NOK = 'norwegian krone'
    SEK = 'swedish krona'
    RON = 'romanian leu'
    BGN = 'bulgarian lev'
    TRY = 'turkish lira'
    ILS = 'israeli new shekel'
    CLP = 'chilean peso'
    PHP = 'philippine peso'
    MXN = 'Mexican peso'
    ZAR = 'South African rand'
    BRL = 'brazilian real'
    MYR = 'Malaysian ringgit'
    IDR = 'indonesian rupiah'
    INR = 'indian rupee'
    KRW = 'Korean won'
    CNY = 'china yuan reminbi'
    XDR = 'Special Drawing Rights'
